#!/usr/bin/env python3
# Event-driven freshness for /opt/bacopy/hourly_stats.json (deployed to the VPS as
# /opt/laplace2/hourly_stats_watch.py, run by systemd as user `laplace`).
#
# WHY: the GUI "TIME RATE" cumulative win-rate and the receiver "safety mode" bet
# gate read /api/hourly-stats, which is just the static JSON regenerated by a
# */10 cron. That is too coarse for safety mode, which must react the moment the
# cumulative crosses 50% at ANY time (not on 10-min/hour boundaries). This watcher
# tails the monitor-bot log and regenerates the JSON within ~3s of each NEW NOW
# result, so the cumulative updates per-NOW.
#
# SAFETY: fully isolated. It does NOT touch the fleet-critical monitor bot. It only
# re-runs the EXISTING generator (hourly_stats_json.py, same output, atomic replace).
# The */10 cron stays as a fallback. If this watcher dies, the JSON merely reverts
# to 10-min freshness; nothing else breaks.
import os
import re
import subprocess
import sys
import time

LOG = "/opt/laplace2/dual_line_pragmatic_bot.log"
GEN = "/opt/laplace2/hourly_stats_json.py"
POLL_SEC = 3.0          # how often we check the log for growth
MIN_REGEN_GAP = 3.0     # debounce: at most one regen per this many seconds

# A new line that can move TODAY's cumulative (same two markers hourly_report.parse
# counts): a v4 (10P) settle, or a 6P forward-signal resolve WIN/LOSE.
RESULT_RE = re.compile(
    rb"\[v4-settle\] posted settled .*result=(?:WIN|LOSE)"
    rb"|resolve [^:]+: pred=[PB] outcome=[PBT] (?:WIN|LOSE)"
)


def regen():
    try:
        subprocess.run(
            [sys.executable, GEN], timeout=30,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    except Exception:
        pass


def main():
    # Start at the current end of file so we only react to NEW results.
    try:
        offset = os.path.getsize(LOG)
    except OSError:
        offset = 0
    last_regen = 0.0
    pending = False
    while True:
        time.sleep(POLL_SEC)
        try:
            size = os.path.getsize(LOG)
        except OSError:
            continue
        if size < offset:      # log rotated/truncated -> restart from top
            offset = 0
        if size > offset:
            try:
                with open(LOG, "rb") as f:
                    f.seek(offset)
                    chunk = f.read(size - offset)
                    offset = f.tell()
            except OSError:
                continue
            if RESULT_RE.search(chunk):
                pending = True
        if pending and (time.time() - last_regen >= MIN_REGEN_GAP):
            regen()
            last_regen = time.time()
            pending = False


if __name__ == "__main__":
    main()
